export const applePurple = '#5856d6'
export const appleSytemGray4 = '#d1d1d6'
export const appleSytemGray4Dark = '#3a3a3c'
export const defaultGray = '#F2F2F2'
export const defaultWhite = '#ffffff'
export const appleRed = '#ff3b30'
export const appleGreen = '#4cd964'
